const cards = [
    {
        img: "images/img/item1.jpg",
        title: "giant Pandas",
        text: "Native to Southwest China",
        icon: "images/svg/banana.svg",
        category: "mammal",

    },
    {
        img: "images/img/item2.jpg",
        title: "Eagles",
        text: "Native to South America",
        icon: "images/svg/fish.svg",
        category: "predator",
    },
    {
        img: "images/img/item3.jpg",
        title: "Gorillas",
        text: "Native to Congo",
        icon: "images/svg/banana.svg",
        category: "mammal",
    },
    {
        img: "images/img/item4.jpg",
        title: "Two-toed Sloth",
        text: "Mesoamerica, South America",
        icon: "images/svg/banana.svg",
        category: "mammal",
    },
    {
        img: "images/img/item5.jpg",
        title: "cheetahs",
        text: "Native to Africa",
        icon: "images/svg/fish.svg",
        category: "predator",
    },
    {
        img: "images/img/item6.jpg",
        title: "Penguins",
        text: "Native to Antarctica",
        icon: "images/svg/fish.svg",
        category: "predator",
    },
    {
        img: "images/img/item7.jpg",
        title: "Giraffe",
        text: "Native to Africa",
        icon: "images/svg/banana.svg",
        category: "mammal",
    },
    {
        img: "images/img/item8.jpg",
        title: "Camel",
        text: "Native to Asia",
        icon: "images/svg/banana.svg",
        category: "mammal",
    },
    {
        img: "images/img/item9.jpg",
        title: "Panther",
        text: "Native to Africa",
        icon: "images/svg/fish.svg",
        category: "predator",
    },
    {
        img: "images/img/item10.jpg",
        title: "Squirrels",
        text: "Native to Russia",
        icon: "images/svg/banana.svg",
        category: "mammal",
    },
    {
        img: "images/img/item11.jpg",
        title: "Bengal tiger",
        text: "Native to India",
        icon: "images/svg/fish.svg",
        category: "predator",
    },
    {
        img: "images/img/item12.jpg",
        title: "Kangaroo",
        text: "Native to Australia",
        icon: "images/svg/banana.svg",
        category: "mammal",
    },
    {
        img: "images/img/item13.jpg",
        title: "Koala",
        text: "Native to Australia",
        icon: "images/svg/banana.svg",
        category: "mammal",
    },
    {
        img: "images/img/item14.jpg",
        title: "Impala",
        text: "Native to Africa",
        icon: "images/svg/banana.svg",
        category: "mammal",
    },
    {
        img: "images/img/item15.jpg",
        title: "Alligators",
        text: "Native to Southeastern U. S",
        icon: "images/svg/fish.svg",
        category: "predator",
    },
    {
        img: "images/img/item16.jpg",
        title: "Rhinos",
        text: "Native to Africa",
        icon: "images/svg/banana.svg",
        category: "mamal",
    },
    {
        img: "images/img/item17.jpg",
        title: "Gazelle",
        text: "Native to Africa",
        icon: "images/svg/banana.svg",
        category: "mamal",
    },
    {
        img: "images/img/item18.jpg",
        title: "Elephant",
        text: "Native to Africa, Asia",
        icon: "images/svg/banana.svg",
        category: "mamal",
    },

]
